spring:
  jpa:
#    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

  profiles:
    include: oauth

  cloud:
    aws:
      credentials:
        profile-name: default
      region:
        static: AP_NORTHEAST_2
      stack:
        auto: false
  data:
    redis:
      host: 43.201.245.61
      port: 6379
  cache:
    type: redis

  servlet:
    multipart:
      max-file-size: 8MB
      max-request-size: 16MB

springdoc:
  swagger-ui:
    path: /api-test
#server:
# ssl:
#   key-store: keystore.p12
#   key-store-password: 120321
#   key-store-type: PKCS12
#   enabled: true
openai :
  api :
    model : gpt-3.5-turbo
    key : ENC(L8Py5aToNuhTwWFyFS4rcAuKvnr7/QIoq1NjGlKBCRgHqWoyLt9AXI8EhO4WXi0D7TTSNFQVSPOg8qq7fKD9JQ==)
    url : https://api.openai.com/v1/chat/completions
